name= input("who are you?")
city=input('where do you live?')
age=input('how old are you?')
hobby=input('what is your hobby?')
movie=input('what is your favourate movie?')
food=('what is your favourate food?')

print("...your details filled by you...")
print("name:", name)
print("city:", city)
print("age:", age)
print("hobby:", hobby)
print("movie:", movie)
print("food:", food)
print("....the end")
